version: '3'

services:
  notes-manager:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://notes_web:3306/notes?createDatabaseIfNotExists=true&useSSL=false&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      notes_web:
          condition: service_healthy
  notes_web:
    image: mysql:8.3.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: notes
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10